[package]
edition = "2018"
name = "scot_property_info"
version = "0.1.0"
[dependencies]
chrono = "*"
csv = "*"
reqwest = { version = "*", features = ["json"] }
structopt = "*"
tokio = { version = "*", features = ["full"] }
urlencoding = "*"

[dependencies.serde]
features = ["derive"]
version = "*"
